### ISSUE TITLE
The naming of the symbols are "backwards"

### ISSUE THREAD

**Issue by aowron** [ts91/kicad-LED_DotMatrix#1]
It seems like the designations of the symbols are backwards; from what I can see in the datasheets, the 1088AS is the common cathode one while 1088BS is the common anode version. Currently, in these symbol libraries the BS version is designated as the common cathode version and 1088AS is designated as the common anode version.

Other than that, a damn nice job! These symbols made my project (a game of life display) way easier.

**Comment by ts91** [comment]
Glad you liked it.

I have the BS (marked HL-M1388BR) version and all I can tell is that my symbol makes perfect sense for it. Looking from the top and aligning the notch on the components side.

Example. If I wish to light up the second LED in the top row, then I must connect pin2 (marked C2 in symbol) to positive and pin13 (marked R1 in symbol) to negative. 

I cannot speak for the AS version, but from what I can tell the only difference between the two is that all the LEDs have been rotated which is reflected in my symbol.

Anyway. Thanks for your feedback :)

**Comment by ChrisToxz** [comment]
I have been struggling with the same confusion, your footprint aligns with the notch to the left side, while the datasheet aligns the notch to the bottom.
Datasheet says if you connect pin 2 & pin 13, that row 7/column 1 will be lit.

Therefore its not matching the datasheet and becomes a bit confusing..
